export const MAIN_ROUTE = '/'
export const SIGNIN_ROUTE = '/sign-in'
export const SIGNUP_ROUTE = '/sign-up'
export const PROFILE_ROUTE = '/profile'
export const ADMIN_ROUTE = '/admin'
export const COACH_ROUTE = '/coach'
export const COACHES_ROUTE = '/coaches'
export const FAQ_ROUTE = '/faq'